import type { Metadata } from "next";
import "./globals.css";
import "./index.css";
import { Inter } from "next/font/google";
import PageLayout from "@/components/layout/PageLayout";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={inter.style}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
